import { promises as fs } from 'fs'


export async function GET() {
    var allBlogs = []
    const blogs = await fs.readdir(process.cwd() + '/db/blogData/');
    blogs.forEach(async (blog) => {
        const data  = await fs.readFile(process.cwd() + `/blogData/${blog}`, "utf-8")
        allBlogs.push(JSON.parse(data))
    })


    allBlogs = [
        {
          title: 'How to learn html',
          description: 'The HyperText Markup Language or HTML is the standard markup language for documents designed to be displayed in a web browser. It defines the content and structure of web content. It is often assisted by technologies such as Cascading Style Sheets (CSS) and scripting languages such as JavaScript. Web browsers receive HTML documents from a web server or from local storage and render the documents into multimedia web pages. HTML describes the structure of a web page semantically and originally included cues for its appearance. HTML elements are the building blocks of HTML pages. With HTML constructs, images and other objects such as interactive forms may be embedded into the rendered page. HTML provides a means to create structured documents by denoting structural semantics for text such as headings, paragraphs, lists, links, quotes, and other items. HTML elements are delineated by tags, written using angle brackets. Tags such as <img> and <input> directly introduce content into the page. Other tags such as <p> and </p> surround and provide information about document text and may include sub-element tags. Browsers do not display the HTML tags but use them to interpret the content of the page. HTML can embed programs written in a scripting language such as JavaScript, which affects the behavior and content of web pages. The inclusion of CSS defines the look and layout of content. The World Wide Web Consortium (W3C), former maintainer of the HTML and current maintainer of the CSS standards, has encouraged the use of CSS over explicit presentational HTML since 1997.[2] A form of HTML, known as HTML5, is used to display video and audio, primarily using the <canvas> element, together with JavaScript.',
          slug: 'How-to-learn-html',
          author: 'Akash shaw'
        },
        {
          title: 'How to learn java',
          description: "Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible. It is a general-purpose programming language intended to let programmers write once, run anywhere (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need to recompile.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but has fewer low-level facilities than either of them. The Java runtime provides dynamic capabilities (such as reflection and runtime code modification) that are typically not available in traditional compiled languages. Java gained popularity shortly after its release, and has been a very popular programming language since then.[18] Java was the third most popular programming language in 2022 according to GitHub[19] and it is ranked fourth on TIOBE index as of October 2023.[20] Although still widely popular, there has been a gradual decline in use of Java in recent years with other languages using JVM gaining popularity.[21] Java was originally developed by James Gosling at Sun Microsystems. It was released in May 1995 as a core component of Sun Microsystems' Java platform. The original and reference implementation Java compilers, virtual machines, and class libraries were originally released by Sun under proprietary licenses. As of May 2007, in compliance with the specifications of the Java Community Process, Sun had relicensed most of its Java technologies under the GPL-2.0-only license. Oracle offers its own HotSpot Java Virtual Machine, however the official reference implementation is the OpenJDK JVM which is free open-source software and used by most developers and is the default JVM for almost all Linux distributions. As of September 2023, Java 21 is the latest version, which is also a long-term support (LTS) version. Java 8, 11, and 17 are previous LTS versions still officially supported.",
          slug: 'How-to-learn-java',
          author: 'Akash biswas'
        },
        {
          title: 'How to learn Javascript',
          description: 'JavaScript is typically used as a client-side scripting language for front end development. In simple terms, this means that developers use JavaScript to build the part of a website that ordinary visitors can see and interact with, also known as the “front end.” While the programming language can technically be used to create complex programs, its primary application lies in web development. Front end programmers typically use JavaScript in conjunction with two markup languages, HTML and CSS, to create all of the elements that a user can see and interact with directly. Most common actions, such as transactions, submitting customer feedback, and even logging in, are facilitated by HTML code. CSS, on the other hand, centers more on formatting and appearance; it allows developers to describe how the HTML should look to a visitor. Both, however, are static. With only HTML and CSS, a web page is unchanging and relatively simplistic. Chart showing that JavaScript is the most popular coding language that companies look for With JavaScript, a website becomes dynamic. Not only does it automate processes that users would, in an HTML-only site, need to perform manually, but it also empowers a website to react to a visitor’s input. Autocorrect functions, slideshows, interactive graphics: these can all be credited to JavaScript working tirelessly in the background. That said, JavaScript’s appeal isn’t confined to its functionality. It’s also one of the most intuitive programming languages to learn and use; often, it’s one of the first that newbie developers learn when they start to code. “JavaScript is very easy to implement,” writes one tech journalist for Web Platform. “All you need to do is put your code in the HTML document and tell the browser that it is JavaScript […] then, JavaScript allows you to create highly responsive interfaces that improve the user experience and provide dynamic functionality, without having to wait for the server to react and show another page.” It’s fast, versatile, and can even help identify and fix problems via its browser support functions.',
          slug: 'How-to-learn-javascript',
          author: 'Akash koiri'
        },
        {
          title: 'How to learn python',
          description: 'Python is the programming language that opens more doors than any other, and the more you understand Python, the more you can do in the 21st Century. With a solid knowledge of Python, you can work in a multitude of jobs and a multitude of industries. Software Engineer, Software Developer, Machine Learning Engineer, AI Engineer, DevOps Engineer, Full Stack Developer, Data Scientist, Project Manager, Systems Administrator, Security Engineer, Tester... The jobs that involve Python are varied and interesting. And there are many of them. The choices you make every day shape your reality and determine who you are, but your life-changing decisions determine who you become. Here at OpenEDG, we believe in the value of education and certification, and in the power of life-changing decisions. Follow one of the OpenEDG Python Institute professional development programs, learn, certify your skills to kickstart your career as a developer, and achieve the ultimate goal – landing your dream job. Complete the course and get an education that will equip you with the skills and knowledge you need in order to succeed in your chosen career. Pass the exam and obtain industry certification, and you will be in possession of the right tools to get the job you want. The right industry-recognized certification opens the right doors, and allows you to take full advantage of all the opportunities you find on the other side',
          slug: 'How-to-learn-python',
          author: 'Akash prasad'
        },
        {
          title: 'How to learn rust',
          description: "Rust is a multi-paradigm, general-purpose programming language that emphasizes performance, type safety, and concurrency. It enforces memory safety, meaning that all references point to valid memory, without requiring the use of automated memory management techniques, such as garbage collection. To simultaneously enforce memory safety and prevent data races, its 'borrow checker' tracks the object lifetime of all references in a program during compilation. Rust was influenced by ideas from functional programming, including immutability, higher-order functions, and algebraic data types. It is popular for systems programming.[13][14][15] Software developer Graydon Hoare created Rust as a personal project while working at Mozilla Research in 2006. Mozilla officially sponsored the project in 2009. In the years following the first stable release in May 2015, Rust was adopted by companies including Amazon, Discord, Dropbox, Google (Alphabet), Meta, and Microsoft. In December 2022, it became the first language other than C and assembly to be supported in the development of the Linux kernel. Rust has been noted for its rapid adoption,[16] and has been studied in programming language theory research.[17][18][19] History Mozilla Foundation headquarters in Mountain View, California Origins (2006–2012) Rust grew out of a personal project begun in 2006 by Mozilla Research employee Graydon Hoare.[20] Mozilla began sponsoring the project in 2009 as a part of the ongoing development of an experimental browser engine called Servo,[21] which was officially announced by Mozilla in 2010.[22][23] During the same year, work shifted from the initial compiler written in OCaml to a self-hosting compiler based on LLVM written in Rust. The new Rust compiler successfully compiled itself in 2011.",
          slug: 'How-to-learn-rust',
          author: 'Akash kumar'
        }
      ]

    return Response.json(allBlogs)
}

